name: HundredDaysChunkLess
version: '${project.version}'
main: dev.sasukector.hundreddayschunkless.HundredDaysChunkLess
api-version: 1.17
authors: [ Sasukector ]
description: This is the core plugin for HundredDaysChunkLess
website: https://sasukector.dev
commands:
  played:
    description: Command to see played time of a player
    usage: /played [playerName]
  toggleDays:
    description: Command to toggle days display
    usage: /toggleDays